Added: display progress while translating; Updated: prepared code for more reasoned translation process

diff --git a/srtranslate b/srtranslate
--- a/srtranslate
+++ b/srtranslate
@@ -67,30 +67,12 @@ is_time_string() { [[ $@ =~ $time_string_regexp ]] && echo "y" || echo "n"; }
 is_empty()       { [[ $@ =~ ^[[:space:]]*$ ]] && echo "y" || echo "n"; }
 is_text()        { ([ "n" = `is_counter $@` ] && [ "n" = `is_time_string $@` ] && [ "n" = `is_empty $@` ]) && echo "y" || echo "n"; }
 
+ends_with_puntuation() { [[ $@ =~ [.!?]$ ]] && echo "y" || echo "n"; }
+
 fname="${3%%.srt}"
 fname="${fname%%_${source_lang}}"
 outfile="${fname}_$target_lang.srt"
 echo -n "" > "$outfile"
-
-min() {
-    local min=10000000
-    for n in $@; do
-        if test $n -lt $min; then
-            min=$n
-        fi
-    done
-    echo "$min"
-}
-
-max() {
-    local max=0
-    for n in $@; do
-        if test $n -gt $max; then
-            max=$n
-        fi
-    done
-    echo "$max"
-}
 
 reformat_line() {
     local orig_line_number=$1
@@ -118,14 +100,47 @@ reformat_line() {
     echo -en "\n"
 }
 
+number_of_lines=0
+while read line; do
+    if [ `is_counter "$line"` = "y" ]; then
+        number_of_lines=$line
+        break
+    fi
+done <<< $(tac "$3")
+
+show_progress() {
+    echo -ne "\rTranslating line $1 / $2..."
+    sleep 1
+}
+
 string_buffer=""
 orig_line_number=0
 orig_max_length=0
-cat "$3" | while read line; do
+id_queue=()
+time_queue=()
+
+dump_queue() {
+    test ${#id_queue[@]} -ne ${#time_queue[@]} && echo "error: id_queue and time_queue have different sizes" >&2 && exit 4
+    # TODO: insert here logic to meaningfully split the translated string
+    local lines=("`reformat_line \"$orig_line_number\" \"$orig_max_length\" \"$string_buffer\"`")
+    # local lines=("`reformat_line \"$orig_line_number\" \"$orig_max_length\" \"$(translate_line \"$string_buffer\")\"`")
+    for i in `seq 0 $((${#id_queue[@]} - 1))`; do
+        echo "${id_queue[$i]}" >> "$outfile"
+        echo "${time_queue[$i]}" >> "$outfile"
+        echo "${lines[$i]}" >> "$outfile"
+        echo "" >> "$outfile"
+    done
+    id_queue=()
+    time_queue=()
+    string_buffer=""
+}
+
+while read line; do
     if [ `is_counter "$line"` = "y" ]; then
-        echo "$line" >> "$outfile"
+        show_progress $line $number_of_lines
+        id_queue+=("$line")
     elif [ `is_time_string "$line"` = "y" ]; then
-        echo "$line" >> "$outfile"
+        time_queue+=("$line")
     elif [ `is_text "$line"` = "y" ]; then
         if test ${#string_buffer} -gt 0; then
             string_buffer="$string_buffer $line"
@@ -135,19 +150,19 @@ cat "$3" | while read line; do
         else
             string_buffer="$line"
             orig_max_length=${#line}
+            orig_line_number=1
         fi
         orig_line_number=$(($orig_line_number + 1))
     else
-        if test ${#string_buffer} -gt 0; then
-            translated="`translate_line $string_buffer`"
-            reformat_line "$orig_line_number" "$orig_max_length" "$translated" >> "$outfile"
+        # TODO: enable joining of subsequent subtitles uncommenting second condition
+        if test ${#string_buffer} -gt 0;then # -a `ends_with_puntuation "$string_buffer"` = "y"; then
+            dump_queue
         fi
-        string_buffer=""
-        echo "$line" >> "$outfile"
     fi
-done < "$3"
+done <<< `cat "$3"`
 
 if test ${#string_buffer} -gt 0; then
-    translated="`translate_line $string_buffer`"
-    reformat_line "$orig_line_number" "$orig_max_length" "$translated" >> "$outfile"
+    dump_queue
 fi
+
+echo " done."
